version: 0.2

env:
  variables:
    CI: "true"
    REPOSITORY_REGION: "eu-central-1"
    ENV: "testenv"
    APP_NAME: "testapp"
    #TERRAFORM_VERSION: "0.14.7"
    TERRAFORM_VERSION: "1.3.3"
    
phases:
  pre_build:
    commands:
      - curl -sSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - export REGISTRY_ID=`aws sts get-caller-identity --output text | awk '{print $1}'`
      - export REPO_NAME="${REGISTRY_ID}.dkr.ecr.${REPOSITORY_REGION}.amazonaws.com/${APP_NAME}-${ENV}"
      - echo "Getting existing tag"
      - pip install jq
      - export SERVICE_ARN=$(aws ecs list-services --cluster test-cluster | jq -r .serviceArns[])
      - export TASKDEF_ARN=$(aws ecs describe-services --cluster test-cluster --service ${SERVICE_ARN} | jq -r .services[].taskDefinition)
      - export EXISTING_TAG=$(aws ecs describe-task-definition --task-definition ${TASKDEF_ARN} | jq -r .taskDefinition.containerDefinitions[].image | tr ':' ' ' | awk '{print $2}')
      - echo "Current version is ${EXISTING_TAG}"
      
  build:
    commands:
      - echo "Build and push docker images"
      - cd "${CODEBUILD_SRC_DIR}/project"
      - export TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}-${ENV}"
      - echo "Building version ${TAG}"
      - make build
      - echo "Build is completed! Added ecs policy"

      - cd "${CODEBUILD_SRC_DIR}"
      - terraform init 
      - terraform destroy --var-file=./project/config.testenv.tfvars -auto-approve -input=false
      # - terraform plan -target=module.ecs --var-file="./project/config/testenv.tfvars" --var-file="./secret.tfvars" -var="image_tag=${TAG}" -no-color -input=false -out plan.out
      # - terraform apply -auto-approve -no-color -input=false plan.out
      # - terraform plan -target=module.ecs --var-file="./project/config/testenv.tfvars" -var="image_tag=${TAG}" -no-color -input=false #-out plan.out
      # - terraform apply -auto-approve -no-color -input=false plan.out
      # - terraform apply -target=module.vpc --var-file=./project/config/testenv.tfvars -auto-approve -no-color -input=false #plan.out
      # - terraform apply -target=module.alb --var-file=./project/config/testenv.tfvars -auto-approve -no-color -input=false #plan.out
      # - terraform apply -target=module.ecs --var-file=./project/config/testenv.tfvars -auto-approve -no-color -input=false #plan.out
      # - terraform destroy --var-file=./project/config.testenv.tfvars -auto-approve -input=false
  post_build:
    commands:
      - | 
        if [ $CODEBUILD_BUILD_SUCCEEDING != 0 ]; then
          NEWTAG=''
          while [ "${NEWTAG}" != "${TAG}" ]; 
          do 
            NEW_ARN=$(aws ecs list-services --cluster test-cluster | jq -r .serviceArns[])
            NEW_TASKDEF=$(aws ecs describe-services --cluster test-cluster --service ${NEW_ARN} | jq -r .services[].taskDefinition)
            NEWTAG=$(aws ecs describe-task-definition --task-definition ${NEW_TASKDEF} | jq -r .taskDefinition.containerDefinitions[].image | tr ':' ' ' | awk '{print $2}')
            echo "Waiting until new image started... Tag: ${TAG} New tag: ${NEWTAG}"
            if [ "${NEWTAG}" != ${TAG} ]; then
              sleep 10
            fi
          done
        else
          echo "Build failed"
        fi
      - echo "Cluster has been deployed"